apiVersion: v1
kind: Secret
metadata:
  name: garmin-secret
type: Opaque
data:
  GARMIN_PASS:  {{.Values.garminScraper.garminPass}}
  SLACK_BOT_TOKEN: {{.Values.garminScraper.slackBotToken}}
  INTERVALS_API_KEY: {{.Values.garminScraper.intervalsApiKey}}
